disable_interior_sun = false
disable_flickering = true
disable_pulse = false
save_log = false
auto_enable = false
no_notifications = false
debug = false
standard_hue = 0.62
standard_saturation = 0.8
standard_value = 0.57
standard_radius = 1.2
colored_hue = 1.0
colored_saturation = 0.9
colored_value = 0.7
colored_radius = 1.1
duration_mult = 2.5
excluded_plugins = [
    "deleted_groundcover.omwaddon",
    "Clean_Argonian Full Helms Lore Integrated.ESP",
    "Baldurwind.omwaddon",
    "Crassified Navigation.omwaddon",
    "LuaMultiMark.omwaddon",
    "S3maphore.esp",
    "Toolgun.omwaddon",
]
excluded_ids = []
output_dir = "/home/s3kshun8/.config/openmw/starwind/override"
save_config = false

[light_overrides]

[ambient_overrides]
